address: "https://mai.ru/education/schedule"
departments:
  inst1: 150
  inst2: 153
  inst3: 157
  inst4: 149
  inst5: 155
  inst6: 160
  inst7: 154
  inst8: 151
  inst9: 152
  inst10: 146
  inst11: 165
  inst12: 164